import { getDbClient, runQuery } from "./dal";

async function initDbSchema() {
    const ddl = `
BEGIN;

CREATE TABLE IF NOT EXISTS users (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 first_name TEXT NOT NULL,
 last_name TEXT NOT NULL,
 email TEXT NOT NULL UNIQUE,
 password TEXT NOT NULL,
 is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS vacations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 destination TEXT NOT NULL,
 description TEXT NOT NULL,
 start_date TIMESTAMPTZ NOT NULL,
 end_date TIMESTAMPTZ NOT NULL,
 price NUMERIC(12,2) NOT NULL CHECK (price > 0 AND price <= 10000),
 image TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS followers (
  user_id BIGINT NOT NULL,
  vacation_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, vacation_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (vacation_id) REFERENCES vacations(id) ON DELETE CASCADE
);

-- helpful indexes for FKs / lookups
CREATE INDEX IF NOT EXISTS idx_vacations_destination
    ON vacations(destination);

CREATE INDEX IF NOT EXISTS idx_vacations_start_date
    ON vacations(start_date);

CREATE INDEX IF NOT EXISTS idx_vacations_end_date
    ON vacations(end_date);

CREATE INDEX IF NOT EXISTS idx_followers_vacation_id
    ON followers(vacation_id);


COMMIT;
    `;

    await runQuery(ddl, [], undefined);
}

async function generateSampleData() {
    const dbClient = await getDbClient();

    try {
        await runQuery("BEGIN;", [], dbClient);

        // Table cleaning
        // await runQuery(
        //     "TRUNCATE TABLE followers, vacations, users RESTART IDENTITY CASCADE;",
        //     [],
        //     dbClient
        // );

        // users
        await runQuery(
            `INSERT INTO users (id, first_name, last_name, email, password, is_admin) VALUES
                (1,  'Admin', 'User',    'admin@example.com',          'admin',     true),
                (2,  'David', 'Cohen',   'david.cohen@example.com',    'password2', false),
                (3,  'Noa',   'Levi',    'noa.levi@example.com',       'password3', false),
                (4,  'Yair',  'Levi',    'yair.levi@example.com',      'password4', false),
                (5,  'Dana',  'Rozin',   'dana.rozin@example.com',     'password5', false),
                (6,  'Amit',  'Katz',    'amit.katz@example.com',      'password6', false),
                (7,  'Roni',  'Bar',     'roni.bar@example.com',       'password7', false),
                (8,  'Eli',   'Mizrahi', 'eli.mizrahi@example.com',    'password8', false),
                (9,  'Tal',   'Halevi',  'tal.halevi@example.com',     'password9', false),
                (10, 'Lior',  'Aviv',    'lior.aviv@example.com',      'password10', false);
            `,
            [],
            dbClient
        );

        // vacations
        await runQuery(
            `INSERT INTO vacations (id, destination, description, start_date, end_date, price, image) VALUES
                (1,  'Paris', 'Romantic city break with museums, cafes and Seine river cruises',
                '2025-03-10 09:00:00+00', '2025-03-17 18:00:00+00', 2599.90, 'paris.jpg'),
                (2,  'New York', 'Urban adventure with shopping, Broadway shows and skyline views',
                '2025-04-01 10:00:00+00', '2025-04-08 20:00:00+00', 3299.00, 'newyork.jpg'),
                (3,  'Rome', 'Historic tour of ancient ruins, charming piazzas and Italian cuisine',
                '2025-05-05 08:00:00+00', '2025-05-12 19:00:00+00', 1999.50, 'rome.jpg'),
                (4,  'Barcelona', 'Beachside vacation with Gaudi architecture, tapas bars and lively streets',
                '2025-06-15 07:00:00+00', '2025-06-22 21:00:00+00', 1899.99, 'barcelona.jpg'),
                (5,  'Bangkok', 'Exotic trip with street food, golden temples and vibrant night markets',
                '2025-07-10 06:00:00+00', '2025-07-20 23:00:00+00', 3499.00, 'bangkok.jpg'),
                (6,  'Tokyo', 'Modern city experience with tech districts, shrines and fresh sushi',
                '2025-08-01 05:00:00+00', '2025-08-12 23:30:00+00', 3999.90, 'tokyo.jpg'),
                (7,  'London', 'Classic city break with museums, green parks and royal landmarks',
                '2025-09-05 09:30:00+00', '2025-09-12 19:30:00+00', 2399.00, 'london.jpg'),
                (8,  'Amsterdam', 'Canal-side holiday with bikes, art museums and cozy cafes',
                '2025-10-10 08:30:00+00', '2025-10-17 18:30:00+00', 2199.50, 'amsterdam.jpg'),
                (9,  'Berlin', 'Cultural city break with history, galleries and lively nightlife',
                '2025-11-01 07:30:00+00', '2025-11-08 20:30:00+00', 2099.00, 'berlin.jpg'),
                (10, 'Athens', 'Mediterranean escape with ancient ruins, sea views and island vibes',
                '2025-12-05 09:00:00+00', '2025-12-11 18:00:00+00', 1799.00, 'athens.jpg');
            `,
            [],
            dbClient
        );

        // followers
        await runQuery(
            `INSERT INTO followers (user_id, vacation_id) VALUES
                (2, 1),
                (3, 1),
                (4, 2),
                (5, 2),
                (6, 3),
                (7, 4),
                (8, 5),
                (9, 6),
                (10, 7),
                (3, 8);
            `,
            [],
            dbClient
        );

        await runQuery(
            `SELECT setval(
                pg_get_serial_sequence('users', 'id'),
                COALESCE((SELECT MAX(id) FROM users), 1),
                true
            );`,
            [],
            dbClient
        );

        await runQuery(
            `SELECT setval(
                pg_get_serial_sequence('vacations', 'id'),
                COALESCE((SELECT MAX(id) FROM vacations), 1),
                true
            );`,
            [],
            dbClient
        );

        await runQuery("COMMIT;", [], dbClient);
    } catch (error) {
        await runQuery("ROLLBACK;", [], dbClient);
        throw error;
    } finally {
        dbClient.release();
    }
}

async function main() {
    try {
        console.log("Starting init DB");

        const dbInfo = await runQuery("SELECT current_database() AS db;");
        console.log("Connected to DB:", dbInfo[0].db);

        await generateSampleData();

        console.log("Done init DB");
    } catch (err) {
        console.error("Fatal error in initDb:");
        console.error(err);
        process.exitCode = 1;
    }
}
main();